version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana_inventario
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - "${PWD}/data:/var/lib/grafana"